site_name: TPOT
site_url: http://epistasislab.github.io/tpot
site_author: Randal S. Olson
site_description: Documentation for TPOT, a Python Automated Machine Learning tool that optimizes machine learning pipelines using genetic programming.

repo_url: https://github.com/rhiever/tpot
edit_uri: edit/master/docs_sources/
docs_dir: docs_sources/
site_dir: docs/
theme: readthedocs

markdown_extensions:
  - tables
  - fenced_code

copyright: Developed by <a href="http://www.randalolson.com">Randal S. Olson</a> and others at the University of Pennsylvania

pages:
- Home: index.md
- Installation: installing.md
- Using TPOT: using.md
- TPOT API: api.md
- Examples: examples.md
- Contributing: contributing.md
- Release Notes: releases.md
- Citing: citing.md
- Support: support.md
- Related: related.md
