site_name: TPOT
site_url: http://rhiever.github.io/tpot
site_author: Randal S. Olson
site_description: TPOT is a Python tool that automatically creates and optimizes machine learning pipelines using genetic programming.

repo_url: https://github.com/rhiever/tpot
edit_uri: edit/master/docs_sources/
docs_dir: docs_sources/
site_dir: docs/
theme: readthedocs

markdown_extensions:
  - tables
  - fenced_code

copyright: Copyright &copy; 2016-Present <a href="http://www.randalolson.com">Randal S. Olson</a>

pages:
- Home: index.md
- Installation: installing.md
- Using TPOT: using.md
- Examples:
  - examples/MNIST_Example.md
  - examples/IRIS_Example.md
  - examples/Boston_Example.md
  - examples/Titanic_Kaggle_Example.md
- Contributing: contributing.md
- Release Notes: releases.md
- Citing: citing.md
- Support: support.md
